lwa4p_dual_configurator:
  lwa4p_blue_global_pose:
    x: 0
    y: 0
    z: 0
    theta: 0
    
  lwa4p_red_global_pose:
    x: 1.3
    y: 0
    z: 0
    theta: 0

lwa4p_blue:
  DH_d:
    d0: 205
    d1: 0
    d2: 0
    d3: 316
    d4: 0
    d5: 318.3

  DH_a:
    a0: 0
    a1: 369.2
    a2: 0
    a3: 0
    a4: 0
    a5: 0
  Q0:
    q0_0: 0
    q0_1: 1.570796327
    q0_2: 1.570796327
    q0_3: 0
    q0_4: 0
    q0_5: 0

lwa4p_red:
  DH_d:
    d0: 205
    d1: 0
    d2: 0
    d3: 365
    d4: 0
    d5: 318.3
    
  DH_a:
    a0: 0
    a1: 500
    a2: 0
    a3: 0
    a4: 0
    a5: 0
  Q0:
    q0_0: 0
    q0_1: 1.570796327
    q0_2: 1.570796327
    q0_3: 0
    q0_4: 0
    q0_5: 0